option(USE_HECTOR_TIMING "Compile with hector_timing support. This will add the USE_HECTOR_TIMING define flag and link to hector_timing." ON)
if(USE_HECTOR_TIMING)
  message(STATUS "Building with hector_timing support.")
  add_definitions(-DUSE_HECTOR_TIMING)
else()
  set(hector_timing_INCLUDE_DIRS)
  set(hector_timing_LIBRARY_DIRS)
  set(hector_timing_LIBRARIES)
  set(hector_timing_EXPORTED_TARGETS)
endif()
